project:
  type: website
  output-dir: docs
  resources:
    - data/*

website:
  title: "EDA + Regresión Exportaciones EEUU (2024-01)"
  navbar:
    left:
      - href: index.qmd
        text: Inicio

format:
  html:
    toc: true

execute:
  warning: false
  message: false
  freeze: auto
